[project]
name = "sc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "accelerate>=0.33",
    "datasets>=2.20",
    "evaluate>=0.4",
    "huggingface-hub>=0.23",
    "scikit-learn>=1.4,<2",
    "tensorflow>=2.20.0",
    "tensorflow-datasets>=4.9.9",
    "transformers>=4.41,<5",
    "wandb>=0.21.3",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
